In [2]:
import sklearn.externals 
from time import time
from sklearn import decomposition
from sklearn.impute import KNNImputer
import sklearn.metrics as skm
from skmultilearn.problem_transform import ClassifierChain
import joblib
from sklearn.metrics import make_scorer
from sklearn.model_selection import LeaveOneOut
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from pandas.plotting import scatter_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from scipy.stats import norm 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import QuantileTransformer
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import hamming_loss
from skmultilearn.problem_transform import LabelPowerset
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
import numpy as np
import copy
from sklearn.linear_model import LogisticRegression, SGDClassifier
from skmultiflow.core import BaseSKMObject, ClassifierMixin, MetaEstimatorMixin, MultiOutputMixin
from skmultiflow.utils import check_random_state
import warnings
warnings.filterwarnings("ignore")

In [3]:
#pip install xlrd

In [4]:
#pip install scikit-multiflow - python 3.8

In [5]:
df = pd.read_excel('meta_dataset_n5_k5.xls')
df = df.drop(['data_id','data_name','run_id','task_id','setup_id','flow_id'], axis = 1)
df

leaves  leaves_branch.mean  leaves_branch.sd  leaves_corrob.mean  \
0         2            1.000000          0.000000            0.500000   
1       511           13.414873          4.583014            0.001957   
2        34            6.235294          2.000891            0.029412   
3        12            3.750000          0.753778            0.083333   
4       685           11.281752          2.673954            0.001460   
..      ...                 ...               ...                 ...   
285   41071           20.970271          5.554298            0.000024   
286   94031           20.639768          4.376983            0.000011   
287   28131           19.268245          4.447649            0.000036   
288    3681           13.742461          2.279269            0.000272   
289    4311           14.194154          1.920248            0.000232   

     leaves_corrob.sd  leaves_homo.mean  leaves_homo.sd  \
0            0.133020      4.000000e+00    0.000000e+00   
1            0.003304      1.307730e+07    4.418819e+07   
2            0.042136      7.448000e+02    8.714009e+02   
3            0.126551      4.613333e+01    1.622867e+01   
4            0.005588      6.863978e+05    1.954417e+06   
..                ...               ...             ...   
285          0.000546      1.561971e+17    1.284196e+19   
286          0.000087      2.352799e+13    1.758731e+15   
287          0.000253      4.150850e+11    1.109654e+13   
288          0.000856      8.650965e+06    1.200670e+07   
289          0.003096      1.010743e+07    1.090150e+07   

     leaves_per_class.mean  leaves_per_class.sd  nodes  ...     t1.sd  \
0                 0.500000             0.000000      1  ...  0.247170   
1                 0.100000             0.107707    510  ...  0.096821   
2                 0.500000             0.041595     33  ...  0.173415   
3                 0.333333             0.166667     11  ...  0.030644   
4                 0.500000             0.021678    684  ...  0.019709   
..                     ...                  ...    ...  ...       ...   
285               0.500000             0.031593  41070  ...       NaN   
286               0.500000             0.001557  94030  ...       NaN   
287               0.142857             0.100286  28130  ...       NaN   
288               0.333333             0.238048   3680  ...       NaN   
289               0.500000             0.120886   4310  ...       NaN   

           t2        t3        t4  \
0    0.158416  0.079208  0.500000   
1    0.005391  0.004717  0.875000   
2    0.164948  0.005155  0.031250   
3    0.073034  0.005618  0.076923   
4    0.002130  0.001065  0.500000   
..        ...       ...       ...   
285  0.000034  0.000029  0.852941   
286  0.000013  0.000003  0.230769   
287  0.000065  0.000044  0.666667   
288  0.000163  0.000127  0.777778   
289  0.000245  0.000245  1.000000   

     one-hot-encoder=sklearn.preprocessing.data.OneHotEncoder  \
0                                                    0          
1                                                    0          
2                                                    1          
3                                                    1          
4                                                    0          
..                                                 ...          
285                                                  0          
286                                                  0          
287                                                  0          
288                                                  0          
289                                                  0          

     variance-thresholding=sklearn.feature_selection.variance_threshold.VarianceThreshold  \
0                                                    0                                      
1                                                    0                                      
2                                    

In [6]:
#exclude meta-features with the percentage of missing values greater than 10%
total = df.isnull().sum().sort_values(ascending=False)
percent_1 = df.isnull().sum() / df.isnull().count()*100
percent_2 = (round(percent_1, 2)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total Nulls', '%'])
missing_data = missing_data.sort_values(by=['Total Nulls'], ascending=False)
missing_data.head(50)

Total Nulls      %
f2.sd                                   230  79.31
f3.sd                                   222  76.55
l2.sd                                   222  76.55
f4.sd                                   222  76.55
l1.sd                                   222  76.55
f1v.sd                                  222  76.55
l3.sd                                   222  76.55
MeanNoiseToSignalRatio                  212  73.10
Quartile3MutualInformation              210  72.41
MinMutualInformation                    210  72.41
Quartile2MutualInformation              210  72.41
Quartile1MutualInformation              210  72.41
Quartile1AttributeEntropy               210  72.41
Quartile3AttributeEntropy               210  72.41
MeanMutualInformation                   210  72.41
MaxAttributeEntropy                     210  72.41
MeanAttributeEntropy                    210  72.41
MinAttributeEntropy                     210  72.41
Quartile2AttributeEntropy               210  72.41
MaxMutualInformation                    210  72.41
n2.sd                                    51  17.59
n2.mean                                  51  17.59
t1.sd                                    44  15.17
n1                                       44  15.17
hubs.sd                                  43  14.83
hubs.mean                                43  14.83
n4.sd                                    41  14.14
n4.mean                                  41  14.14
t1.mean                                  41  14.14
density                                  39  13.45
cls_coef                                 39  13.45
n3.sd                                    38  13.10
n3.mean                                  38  13.10
lsc                                      38  13.10
Quartile1MeansOfNumericAtts              22   7.59
MeanMeansOfNumericAtts                   22   7.59
MaxKurtosisOfNumericAtts                 22   7.59
MeanKurtosisOfNumericAtts                22   7.59
MaxStdDevOfNumericAtts                   22   7.59
Quartile3SkewnessOfNumericAtts           22   7.59
Quartile3MeansOfNumericAtts              22   7.59
MeanSkewnessOfNumericAtts                22   7.59
MeanStdDevOfNumericAtts                  22   7.59
MaxSkewnessOfNumericAtts                 22   7.59
MinKurtosisOfNumericAtts                 22   7.59
Quartile1StdDevOfNumericAtts             22   7.59
MaxMeansOfNumericAtts                    22   7.59
MinSkewnessOfNumericAtts                 22   7.59
MinStdDevOfNumericAtts                   22   7.59
Quartile3KurtosisOfNumericAtts           22   7.59

In [7]:
df = df.drop(['f2.sd','f3.sd','l2.sd','f4.sd','l1.sd','f1v.sd','l3.sd','MeanNoiseToSignalRatio',
             'Quartile3MutualInformation','MinMutualInformation','Quartile2MutualInformation','Quartile1MutualInformation',
             'Quartile1AttributeEntropy','Quartile3AttributeEntropy','MeanMutualInformation','MaxAttributeEntropy',
             'MeanAttributeEntropy','MinAttributeEntropy','Quartile2AttributeEntropy','MaxMutualInformation',      
             'n2.mean','n2.sd', 'n1','t1.sd','hubs.mean','hubs.sd',
              'n4.sd','n4.mean','t1.mean','density','cls_coef','n3.sd','n3.mean','lsc'
             ], axis = 1)
df

leaves  leaves_branch.mean  leaves_branch.sd  leaves_corrob.mean  \
0         2            1.000000          0.000000            0.500000   
1       511           13.414873          4.583014            0.001957   
2        34            6.235294          2.000891            0.029412   
3        12            3.750000          0.753778            0.083333   
4       685           11.281752          2.673954            0.001460   
..      ...                 ...               ...                 ...   
285   41071           20.970271          5.554298            0.000024   
286   94031           20.639768          4.376983            0.000011   
287   28131           19.268245          4.447649            0.000036   
288    3681           13.742461          2.279269            0.000272   
289    4311           14.194154          1.920248            0.000232   

     leaves_corrob.sd  leaves_homo.mean  leaves_homo.sd  \
0            0.133020      4.000000e+00    0.000000e+00   
1            0.003304      1.307730e+07    4.418819e+07   
2            0.042136      7.448000e+02    8.714009e+02   
3            0.126551      4.613333e+01    1.622867e+01   
4            0.005588      6.863978e+05    1.954417e+06   
..                ...               ...             ...   
285          0.000546      1.561971e+17    1.284196e+19   
286          0.000087      2.352799e+13    1.758731e+15   
287          0.000253      4.150850e+11    1.109654e+13   
288          0.000856      8.650965e+06    1.200670e+07   
289          0.003096      1.010743e+07    1.090150e+07   

     leaves_per_class.mean  leaves_per_class.sd  nodes  ...   l3.mean  \
0                 0.500000             0.000000      1  ...  0.000000   
1                 0.100000             0.107707    510  ...  0.046774   
2                 0.500000             0.041595     33  ...  0.396907   
3                 0.333333             0.166667     11  ...  0.000000   
4                 0.500000             0.021678    684  ...  0.100548   
..                     ...                  ...    ...  ...       ...   
285               0.500000             0.031593  41070  ...  0.067120   
286               0.500000             0.001557  94030  ...  0.074462   
287               0.142857             0.100286  28130  ...  0.102027   
288               0.333333             0.238048   3680  ...  0.310311   
289               0.500000             0.120886   4310  ...  0.132457   

           t2        t3        t4  \
0    0.158416  0.079208  0.500000   
1    0.005391  0.004717  0.875000   
2    0.164948  0.005155  0.031250   
3    0.073034  0.005618  0.076923   
4    0.002130  0.001065  0.500000   
..        ...       ...       ...   
285  0.000034  0.000029  0.852941   
286  0.000013  0.000003  0.230769   
287  0.000065  0.000044  0.666667   
288  0.000163  0.000127  0.777778   
289  0.000245  0.000245  1.000000   

     one-hot-encoder=sklearn.preprocessing.data.OneHotEncoder  \
0                                                    0          
1                                                    0          
2                                                    1          
3                                                    1          
4                                                    0          
..                                                 ...          
285                                                  0          
286                                                  0          
287                                                  0          
288                                                  0          
289                                                  0          

     variance-thresholding=sklearn.feature_selection.variance_threshold.VarianceThreshold  \
0                                                    0                                      
1                                                    0                                      
2                                    

In [8]:
total = df.isnull().sum().sort_values(ascending=False)
percent_1 = df.isnull().sum() / df.isnull().count()*100
percent_2 = (round(percent_1, 2)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total Nulls', '%'])
missing_data = missing_data.sort_values(by=['Total Nulls'], ascending=False)
missing_data.head(40)

Total Nulls     %
Quartile3SkewnessOfNumericAtts           22  7.59
MaxStdDevOfNumericAtts                   22  7.59
MinMeansOfNumericAtts                    22  7.59
Quartile2MeansOfNumericAtts              22  7.59
MinStdDevOfNumericAtts                   22  7.59
Quartile1StdDevOfNumericAtts             22  7.59
Quartile1SkewnessOfNumericAtts           22  7.59
Quartile1MeansOfNumericAtts              22  7.59
Quartile1KurtosisOfNumericAtts           22  7.59
MinSkewnessOfNumericAtts                 22  7.59
Quartile2KurtosisOfNumericAtts           22  7.59
MinKurtosisOfNumericAtts                 22  7.59
MaxSkewnessOfNumericAtts                 22  7.59
MeanStdDevOfNumericAtts                  22  7.59
Quartile2SkewnessOfNumericAtts           22  7.59
MeanMeansOfNumericAtts                   22  7.59
Quartile3StdDevOfNumericAtts             22  7.59
MeanKurtosisOfNumericAtts                22  7.59
Quartile3MeansOfNumericAtts              22  7.59
Quartile3KurtosisOfNumericAtts           22  7.59
MaxKurtosisOfNumericAtts                 22  7.59
Quartile2StdDevOfNumericAtts             22  7.59
MaxMeansOfNumericAtts                    22  7.59
MeanSkewnessOfNumericAtts                22  7.59
f2.mean                                  16  5.52
f1.mean                                  11  3.79
f1.sd                                    11  3.79
nodes_repeated.sd                        10  3.45
tree_imbalance.sd                         9  3.10
nodes_per_level.sd                        9  3.10
nodes                                     0  0.00
NumberOfNumericFeatures                   0  0.00
leaves_per_class.sd                       0  0.00
leaves_per_class.mean                     0  0.00
leaves_homo.sd                            0  0.00
leaves_homo.mean                          0  0.00
leaves_corrob.sd                          0  0.00
leaves_corrob.mean                        0  0.00
leaves_branch.sd                          0  0.00
tree_shape.sd                             0  0.00

In [9]:
columns_to_impute = [
    "Quartile3KurtosisOfNumericAtts",
    "Quartile3MeansOfNumericAtts",
    "Quartile1MeansOfNumericAtts",
    "Quartile1SkewnessOfNumericAtts",
    "Quartile1StdDevOfNumericAtts",
    "Quartile3SkewnessOfNumericAtts",
    "Quartile2StdDevOfNumericAtts",
    "Quartile2SkewnessOfNumericAtts",
    "Quartile2MeansOfNumericAtts",
    "Quartile1KurtosisOfNumericAtts",
    "MaxKurtosisOfNumericAtts",
    "MaxMeansOfNumericAtts",
    "MinMeansOfNumericAtts",
    "Quartile3StdDevOfNumericAtts",
    "Quartile2KurtosisOfNumericAtts",
    "MinSkewnessOfNumericAtts",
    "MinKurtosisOfNumericAtts",
    "MeanStdDevOfNumericAtts",
    "MeanSkewnessOfNumericAtts",
    "MeanMeansOfNumericAtts",
    "MeanKurtosisOfNumericAtts",
    "MaxStdDevOfNumericAtts",
    "MaxSkewnessOfNumericAtts",
    "MinStdDevOfNumericAtts"
]

# Impute missing values with 0 for the specified columns
df[columns_to_impute] = df[columns_to_impute].fillna(0)

In [10]:
total = df.isnull().sum().sort_values(ascending=False)
percent_1 = df.isnull().sum() / df.isnull().count()*100
percent_2 = (round(percent_1, 2)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total Nulls', '%'])
missing_data = missing_data.sort_values(by=['Total Nulls'], ascending=False)
missing_data.head(40)

Total Nulls     %
f2.mean                                16  5.52
f1.sd                                  11  3.79
f1.mean                                11  3.79
nodes_repeated.sd                      10  3.45
nodes_per_level.sd                      9  3.10
tree_imbalance.sd                       9  3.10
nodes_per_attr                          0  0.00
leaves_branch.sd                        0  0.00
leaves_corrob.mean                      0  0.00
leaves_corrob.sd                        0  0.00
leaves_homo.mean                        0  0.00
leaves_homo.sd                          0  0.00
leaves_per_class.mean                   0  0.00
leaves_per_class.sd                     0  0.00
nodes                                   0  0.00
nodes_repeated.mean                     0  0.00
nodes_per_inst                          0  0.00
nodes_per_level.mean                    0  0.00
ClassEntropy                            0  0.00
tree_depth.mean                         0  0.00
tree_depth.sd                           0  0.00
tree_imbalance.mean                     0  0.00
tree_shape.mean                         0  0.00
tree_shape.sd                           0  0.00
var_importance.mean                     0  0.00
AutoCorrelation                         0  0.00
MeanSkewnessOfNumericAtts               0  0.00
Dimensionality                          0  0.00
MajorityClassPercentage                 0  0.00
MajorityClassSize                       0  0.00
MaxKurtosisOfNumericAtts                0  0.00
MaxMeansOfNumericAtts                   0  0.00
MaxNominalAttDistinctValues             0  0.00
MaxSkewnessOfNumericAtts                0  0.00
MaxStdDevOfNumericAtts                  0  0.00
MeanKurtosisOfNumericAtts               0  0.00
MeanMeansOfNumericAtts                  0  0.00
MeanNominalAttDistinctValues            0  0.00
leaves_branch.mean                      0  0.00
MeanStdDevOfNumericAtts                 0  0.00

In [11]:
columns_to_impute = [
'f2.mean','f1.sd', 'f1.mean','nodes_repeated.sd','nodes_per_level.sd','tree_imbalance.sd']
subset_df = df[columns_to_impute]
imputer = KNNImputer(n_neighbors=5)
df[columns_to_impute] = imputer.fit_transform(subset_df)

In [12]:
total = df.isnull().sum().sort_values(ascending=False)
percent_1 = df.isnull().sum() / df.isnull().count()*100
percent_2 = (round(percent_1, 2)).sort_values(ascending=False)
missing_data = pd.concat([total, percent_2], axis=1, keys=['Total Nulls', '%'])
missing_data = missing_data.sort_values(by=['Total Nulls'], ascending=False)
missing_data.head(40)

Total Nulls    %
leaves                                  0  0.0
nodes_per_inst                          0  0.0
leaves_branch.sd                        0  0.0
leaves_corrob.mean                      0  0.0
leaves_corrob.sd                        0  0.0
leaves_homo.mean                        0  0.0
leaves_homo.sd                          0  0.0
leaves_per_class.mean                   0  0.0
leaves_per_class.sd                     0  0.0
nodes                                   0  0.0
nodes_per_attr                          0  0.0
nodes_per_level.mean                    0  0.0
PercentageOfSymbolicFeatures            0  0.0
nodes_per_level.sd                      0  0.0
nodes_repeated.mean                     0  0.0
nodes_repeated.sd                       0  0.0
tree_depth.mean                         0  0.0
tree_depth.sd                           0  0.0
tree_imbalance.mean                     0  0.0
tree_imbalance.sd                       0  0.0
tree_shape.mean                         0  0.0
var_importance.mean                     0  0.0
tree_shape.sd                           0  0.0
var_importance.sd                       0  0.0
MinorityClassPercentage                 0  0.0
AutoCorrelation                         0  0.0
ClassEntropy                            0  0.0
Dimensionality                          0  0.0
MajorityClassPercentage                 0  0.0
MajorityClassSize                       0  0.0
MaxKurtosisOfNumericAtts                0  0.0
MaxMeansOfNumericAtts                   0  0.0
MaxNominalAttDistinctValues             0  0.0
MaxSkewnessOfNumericAtts                0  0.0
MaxStdDevOfNumericAtts                  0  0.0
MeanKurtosisOfNumericAtts               0  0.0
MeanMeansOfNumericAtts                  0  0.0
MeanNominalAttDistinctValues            0  0.0
MeanSkewnessOfNumericAtts               0  0.0
MeanStdDevOfNumericAtts                 0  0.0

In [14]:
X_orig = df.iloc[:,0:86].to_numpy()
print("entry", df.iloc[:,0:86].columns)

Y_orig = df.iloc[:,[86,87,88,89,90,91]].to_numpy()  
print("labels", df.iloc[:,[86,87,88,89,90,91]].columns)

entry Index(['leaves', 'leaves_branch.mean', 'leaves_branch.sd',
       'leaves_corrob.mean', 'leaves_corrob.sd', 'leaves_homo.mean',
       'leaves_homo.sd', 'leaves_per_class.mean', 'leaves_per_class.sd',
       'nodes', 'nodes_per_attr', 'nodes_per_inst', 'nodes_per_level.mean',
       'nodes_per_level.sd', 'nodes_repeated.mean', 'nodes_repeated.sd',
       'tree_depth.mean', 'tree_depth.sd', 'tree_imbalance.mean',
       'tree_imbalance.sd', 'tree_shape.mean', 'tree_shape.sd',
       'var_importance.mean', 'var_importance.sd', 'AutoCorrelation',
       'ClassEntropy', 'Dimensionality', 'MajorityClassPercentage',
       'MajorityClassSize', 'MaxKurtosisOfNumericAtts',
       'MaxMeansOfNumericAtts', 'MaxNominalAttDistinctValues',
       'MaxSkewnessOfNumericAtts', 'MaxStdDevOfNumericAtts',
       'MeanKurtosisOfNumericAtts', 'MeanMeansOfNumericAtts',
       'MeanNominalAttDistinctValues', 'MeanSkewnessOfNumericAtts',
       'MeanStdDevOfNumericAtts', 'MinKurtosisOfNumericAtts',
    

In [15]:
transformer = QuantileTransformer(output_distribution='normal')

In [16]:
class ClassifierChain(BaseSKMObject, ClassifierMixin, MetaEstimatorMixin, MultiOutputMixin):
    """ Classifier Chains for multi-label learning.

    Parameters
    ----------
    base_estimator: skmultiflow.core.BaseSKMObject or sklearn.BaseEstimator (default=LogisticRegression)
        Each member of the ensemble is an instance of the base estimator

    order : str (default=None)
        `None` to use default order, 'random' for random order.

    random_state: int, RandomState instance or None, optional (default=None)
        If int, random_state is the seed used by the random number generator;
        If RandomState instance, random_state is the random number generator;
        If None, the random number generator is the RandomState instance used by `np.random`.

    Examples
    --------
    >>> from skmultiflow.data import make_logical
    >>>
    >>> X, Y = make_logical(random_state=1)
    >>>
    >>> print("TRUE: ")
    >>> print(Y)
    >>> print("vs")
    >>>
    >>> print("CC")
    >>> cc = ClassifierChain(SGDClassifier(max_iter=100, loss='log', random_state=1))
    >>> cc.fit(X, Y)
    >>> print(cc.predict(X))
    >>>
    >>> print("RCC")
    >>> cc = ClassifierChain(SGDClassifier(max_iter=100, loss='log', random_state=1), order='random', random_state=1)
    >>> cc.fit(X, Y)
    >>> print(cc.predict(X))
    >>>
    TRUE:
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]
    vs
    CC
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]
    RCC
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]



    Notes
    -----
    Classifier Chains [1]_ is a popular method for multi-label learning. It exploits correlation between labels
    by incrementally building binary classifiers for each label.

    scikit-learn also includes 'ClassifierChain'. A difference is probabilistic extensions are included here.


    References
    ----------
    .. [1] Read, Jesse, Bernhard Pfahringer, Geoff Holmes, and Eibe Frank. "Classifier chains for multi-label
       classification." In Joint European Conference on Machine Learning and Knowledge Discovery in Databases,
       pp. 254-269. Springer, Berlin, Heidelberg, 2009.

    """

    # TODO: much of this can be shared with Regressor Chains, probably should use a base class to inherit here.

    def __init__(self, base_estimator=LogisticRegression(), order=None, random_state=None):
        super().__init__()
        self.base_estimator = base_estimator
        self.order = order
        self.random_state = random_state
        self.chain = None
        self.ensemble = None
        self.L = None
        self._random_state = None   # This is the actual random_state object used internally
        self.__configure()

    def __configure(self):
        self.ensemble = None
        self.L = -1
        self._random_state = check_random_state(self.random_state)

    def fit(self, X, y, classes=None, sample_weight=None):
        """ Fit the model.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The features to train the model.

        y: numpy.ndarray of shape (n_samples, n_targets)
            An array-like with the labels of all samples in X.

        classes: Not used (default=None)

        sample_weight: Not used (default=None)

        Returns
        -------
        self

        """
        N, self.L = y.shape
        L = self.L
        N, D = X.shape

        self.chain = np.arange(L)
        if self.order == 'random':
            self._random_state.shuffle(self.chain)

        # Set the chain order
        y = y[:, self.chain]

        # Train
        self.ensemble = [copy.deepcopy(self.base_estimator) for _ in range(L)]
        XY = np.zeros((N, D + L-1))
        XY[:, 0:D] = X
        XY[:, D:] = y[:, 0:L - 1]
        for j in range(self.L):
            self.ensemble[j].fit(XY[:, 0:D + j], y[:, j])
        return self

    def partial_fit(self, X, y, classes=None, sample_weight=None):
        """ Partially (incrementally) fit the model.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The features to train the model.

        y: numpy.ndarray of shape (n_samples)
            An array-like with the labels of all samples in X.

        classes: Not used (default=None)

        sample_weight: NOT used (default=None)

        Returns
        -------
        self

        """
        if self.ensemble is None:
            # This is the first time that the model is fit
            self.fit(X, y)
            return self

        N, self.L = y.shape
        L = self.L
        N, D = X.shape

        # Set the chain order
        y = y[:, self.chain]

        XY = np.zeros((N, D + L-1))
        XY[:, 0:D] = X
        XY[:, D:] = y[:, 0:L - 1]
        for j in range(L):
            self.ensemble[j].partial_fit(XY[:, 0:D + j], y[:, j])

        return self

    def predict(self, X):
        """ Predict classes for the passed data.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The set of data samples to predict the labels for.

        Returns
        -------
        A numpy.ndarray with all the predictions for the samples in X.

        """
        N, D = X.shape
        Y = np.zeros((N, self.L))
        for j in range(self.L):
            if j > 0:
                X = np.column_stack([X, Y[:, j-1]])
            Y[:, j] = self.ensemble[j].predict(X)

        # Unset the chain order (back to default)
        return Y[:, np.argsort(self.chain)]

    def predict_proba(self, X):
        """ Estimates the probability of each sample in X belonging to each of the class-labels.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The matrix of samples one wants to predict the class probabilities for.

        Returns
        -------
        A numpy.ndarray of shape (n_samples, n_labels), in which each outer entry is associated with the X entry of the
        same index. And where the list in index [i] contains len(self.target_values) elements, each of which represents
        the probability that the i-th sample of X belongs to a certain class-label.

        Notes
        -----
        Returns marginals [P(y_1=1|x),...,P(y_L=1|x,y_1,...,y_{L-1})]
        i.e., confidence predictions given inputs, for each instance.

        This function suitable for multi-label (binary) data
        only at the moment (may give index-out-of-bounds error if
        uni- or multi-target (of > 2 values) data is used in training).
        """
        N, D = X.shape
        Y = np.zeros((N, self.L))
        for j in range(self.L):
            if j > 0:
                X = np.column_stack([X, Y[:, j-1]])
            Y[:, j] = self.ensemble[j].predict_proba(X)[:, 1]
        return Y

    def reset(self):
        self.__configure()
        return self

    def _more_tags(self):
        return {'multioutput': True,
                'multioutput_only': True}


def P(y, x, cc, payoff=np.prod):
    """ Payoff function, P(Y=y|X=x)

        What payoff do we get for predicting y | x, under model cc.

        Parameters
        ----------
        x: input instance
        y: its true labels
        cc: a classifier chain
        payoff: payoff function

        Returns
        -------
        A single number; the payoff of predicting y | x.
    """
    D = len(x)
    L = len(y)

    p = np.zeros(L)
    xy = np.zeros(D + L)
    xy[0:D] = x.copy()
    for j in range(L):
        P_j = cc.ensemble[j].predict_proba(xy[0:D+j].reshape(1, -1))[0]  # e.g., [0.9, 0.1] wrt 0, 1
        xy[D+j] = y[j]                                           # e.g., 1
        p[j] = P_j[y[j]]                                         # e.g., 0.1
                                                                 # or, y[j] = 0 is predicted with probability p[j] = 0.9
    return payoff(p)

In [17]:
#ClassifierChain
from skmultilearn.problem_transform import ClassifierChain
cv = LeaveOneOut()
y_true, y_pred = list(), list()
count = 0
for train_ix, test_ix in cv.split(X_orig):
        count += 1
        X_train, X_test = X_orig[train_ix, :], X_orig[test_ix, :]
        y_train, y_test = Y_orig[train_ix], Y_orig[test_ix]
        X_train_folds = transformer.fit_transform(X_train)
        X_test_folds= transformer.transform(X_test)
        print("Entry", X_test_folds)
        clf = ClassifierChain(DecisionTreeClassifier(criterion='entropy', random_state=17,  min_samples_leaf=10))
        clf.fit(X_train_folds, y_train)
        #clf.base_estimator.fit(X_train_folds, y_train)
        yhat = clf.predict(X_test_folds)
        #print("Output", count,that)
        print("Output", count,yhat.toarray())
        y_true.append(y_test[0])
        y_pred.append(yhat[0].toarray().ravel())

print("f1",f1_score(y_true, y_pred,average='macro'))
print("acc",accuracy_score(y_true, y_pred))
print("precision", precision_score(y_true, y_pred,average='macro'))
print("hamming",hamming_loss(y_true, y_pred))
print(skm.multilabel_confusion_matrix(y_true, y_pred))

Entry [[-5.19933758e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
   1.27132003e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
  -5.19933758e+00 -5.19933758e+00 -2.87416864e+00 -1.41800799e+00
  -5.19933758e+00 -1.83102868e+00 -5.19933758e+00 -1.63272919e+00
  -5.19933758e+00 -5.19933758e+00  5.19933758e+00  2.64832565e-01
   5.19933758e+00 -5.19933758e+00 -3.37007679e-01  1.31328749e+00
   1.78543910e-01 -2.54694753e-01  1.40391085e+00  2.43263067e-01
  -1.41779714e+00 -9.64642612e-01 -1.14953089e-01 -5.19933758e+00
  -8.06570002e-01 -5.48466372e-02 -3.68580607e-01 -3.63067624e-02
  -5.19933758e+00  1.67459499e-02  1.61790463e-02  6.58790415e-01
   8.86987878e-01 -2.01538181e-01  1.49471900e+00  9.87218257e-01
   1.42553491e-01 -9.88481957e-01  2.21282487e+00 -5.19933758e+00
   3.37007679e-01 -1.42576847e+00 -5.19933758e+00 -5.19933758e+00
  -1.36069179e+00  1.69393425e+00  2.67534323e+00 -5.19933758e+00
  -5.19933758e+00 -1.42978834e+00  1.42978834e+00  1.89588223e-01
   6

In [18]:
#LabelPowerset
cv = LeaveOneOut()
y_true, y_pred = list(), list()
count = 0
for train_ix, test_ix in cv.split(X_orig):
        count += 1
        X_train, X_test = X_orig[train_ix, :], X_orig[test_ix, :]
        y_train, y_test = Y_orig[train_ix], Y_orig[test_ix]
        X_train_folds = transformer.fit_transform(X_train)
        X_test_folds= transformer.transform(X_test)
        print("Entry", X_test_folds)
        clf = LabelPowerset(DecisionTreeClassifier(criterion='entropy', random_state=17,  min_samples_leaf=10))
        clf.fit(X_train_folds, y_train)
        yhat = clf.predict(X_test_folds)
        print("Output", count,yhat.toarray())
        y_true.append(y_test[0])
        y_pred.append(yhat[0].toarray().ravel())
print("f1",f1_score(y_true, y_pred,average='macro'))
print("acc",accuracy_score(y_true, y_pred))
print("precision", precision_score(y_true, y_pred,average='macro'))
print("hamming",hamming_loss(y_true, y_pred))
print(skm.multilabel_confusion_matrix(y_true, y_pred))

Entry [[-5.19933758e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
   1.27132003e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
  -5.19933758e+00 -5.19933758e+00 -2.87416864e+00 -1.41800799e+00
  -5.19933758e+00 -1.83102868e+00 -5.19933758e+00 -1.63272919e+00
  -5.19933758e+00 -5.19933758e+00  5.19933758e+00  2.64832565e-01
   5.19933758e+00 -5.19933758e+00 -3.37007679e-01  1.31328749e+00
   1.78543910e-01 -2.54694753e-01  1.40391085e+00  2.43263067e-01
  -1.41779714e+00 -9.64642612e-01 -1.14953089e-01 -5.19933758e+00
  -8.06570002e-01 -5.48466372e-02 -3.68580607e-01 -3.63067624e-02
  -5.19933758e+00  1.67459499e-02  1.61790463e-02  6.58790415e-01
   8.86987878e-01 -2.01538181e-01  1.49471900e+00  9.87218257e-01
   1.42553491e-01 -9.88481957e-01  2.21282487e+00 -5.19933758e+00
   3.37007679e-01 -1.42576847e+00 -5.19933758e+00 -5.19933758e+00
  -1.36069179e+00  1.69393425e+00  2.67534323e+00 -5.19933758e+00
  -5.19933758e+00 -1.42978834e+00  1.42978834e+00  1.89588223e-01
   6

Entry [[-0.26865596 -0.16790399  0.3856048   0.26855104 -0.13376369 -0.01291903
   0.06940913  5.19933758 -0.80017207 -0.26865596  0.12800104  1.27604338
  -0.51650444 -0.42549926  0.10171678  0.5397452  -0.13662531  0.35033302
  -0.21561246  0.45080157  0.33749251  0.63270205  0.83051088  0.58967635
   0.83553721 -0.43346347  0.40027873  0.4239671  -1.02459239 -0.83667055
   0.15941427 -5.19933758 -0.14298652  0.17474452 -0.39117449  0.19979414
  -5.19933758  0.40821095  0.3416602   0.20198653  1.21521826 -0.20153818
   0.58240023  1.56351457 -0.01994179 -0.60506036  1.42978834 -5.19933758
  -0.81828504 -1.00999017 -5.19933758 -5.19933758 -0.83051088  0.86163412
   1.71249462 -5.19933758 -5.19933758 -0.98848196  0.99560019 -0.0232576
   0.99394756  0.10951044  1.34391858 -0.02801285  0.60827515  0.56893772
   0.60203474 -0.41170514  0.37077334  0.25789827  0.39086109 -5.19933758
  -0.24009397  0.358164    0.18660955 -0.14669385  1.10300821  0.82839539
   0.13424111  0.7234282   1.9374

Output 47 [[0 0 0 1 0 0]]
Entry [[-0.03046721 -0.03870789 -0.21446857  0.03039214 -0.37561772 -0.12782209
  -0.19464399  5.19933758  0.51802054 -0.03046721  0.17288083  2.18553942
  -0.02769672 -0.00963466  0.14643445  0.50464173 -0.03913373 -0.23774795
   0.07404453 -0.43358204 -0.01281977  0.41671627  0.63140189  0.77814405
  -0.40524132  0.41225354  0.53843354 -0.45045853 -1.18476314 -0.77043479
   0.27115373 -5.19933758 -3.12054529  0.19989945 -0.21952436  0.44280525
  -5.19933758 -2.33370444  0.40974403  0.71216982  1.65834324 -0.20153818
  -1.03288922  1.59923754  0.90086965 -0.37409541  1.75149251 -5.19933758
  -0.62609901 -1.05954455 -5.19933758 -5.19933758 -1.19358872  1.17602889
   2.03253915 -5.19933758 -5.19933758 -1.11724663  1.11724663  0.26102189
   1.53330313 -1.97071671  1.37424976  0.04444136  0.91709335 -2.5061543
   0.78854169 -0.31609524  0.58594074 -2.87965603  0.44280088 -5.19933758
   0.74225743 -0.74225732 -0.1071349   0.39603396  0.48960122  0.58861395
  -0.64

Output 56 [[0 0 0 0 1 0]]
Entry [[ 0.89037625  0.71831767  0.72861589 -0.89043077 -0.55957179  0.87418753
   0.94460457  5.19933758 -5.19933758  0.89037625  0.41267513 -0.62644871
   0.8130563   0.92325513  0.41267513  0.34092927  0.71817982  0.75545646
  -0.90001859 -0.87614172 -0.7939513  -0.82874986 -0.80017207  0.11938421
  -0.74040218  0.77769126 -0.51841799 -0.83785406  0.67732529 -1.70832166
  -0.18818602 -5.19933758 -1.06024561  0.42121303 -1.5356535  -0.13630965
  -5.19933758 -0.96893622  0.27250481 -0.29375419 -1.62502715 -0.20153818
   0.43133049 -0.09245133  1.53683021  1.14598729  0.03046721 -5.19933758
   0.80618031  0.74159404 -5.19933758 -5.19933758  0.88714656 -5.19933758
  -0.38813428 -5.19933758 -5.19933758  0.93999091 -0.93324314 -0.43192906
  -0.20875438  0.09473675 -0.36324664 -1.19735488 -0.18602808 -0.77991761
   0.16608247 -1.66089782 -0.09314051 -1.06655009 -0.03616116 -5.19933758
   1.38544084 -1.34215357  1.68010508 -1.00470036  1.33590731  1.4697142
   0.56

Output 65 [[0 0 0 0 0 1]]
Entry [[-0.17938057  0.26201893  0.50956222  0.1838047   0.62990343  0.15679352
   0.18865162  5.19933758  2.20901046 -0.17938057 -0.76762781 -1.48971317
  -0.52375863 -0.39456485 -0.6992833  -0.49868898  0.27025856  0.43036472
  -0.53068454  1.45097609 -0.09771226  1.28151705 -0.8679592  -0.8944963
   1.31144417 -5.19933758 -0.38651497  5.19933758  0.79851764  2.03499919
   1.11274882 -5.19933758  2.08849358  1.43476905  2.21719733  0.62918319
  -5.19933758  2.63756386  1.22068197  0.35993611 -0.02881782 -0.20153818
  -1.87472148 -0.4290857  -1.67420427 -1.41384503  0.03046721 -5.19933758
   0.8743192   0.63980742 -5.19933758 -5.19933758  0.93999091 -5.19933758
  -0.42119717 -5.19933758 -5.19933758  0.98141346 -0.98141346  2.49692175
   0.41636592  2.40735302  0.64148657  5.19933758  0.12222279  5.19933758
   0.46628417  2.6736313   0.10760876  2.70052807  0.54447432 -5.19933758
  -5.19933758  5.19933758  0.59275987 -1.08192081 -1.64966954 -5.19933758
  -0.97

Output 74 [[0 0 0 0 0 1]]
Entry [[-5.19933758 -5.19933758 -5.19933758  5.19933758 -5.19933758 -5.19933758
  -5.19933758  5.19933758 -5.19933758 -5.19933758 -2.11158311 -1.85240884
  -5.19933758 -0.92210345 -5.19933758 -0.61024182 -5.19933758 -5.19933758
   5.19933758  0.9754018   5.19933758 -5.19933758  0.03482132  1.7316644
   1.46909766  0.98141346  0.38520946 -1.08532491 -0.5894558   1.22034548
   1.18520077 -5.19933758  1.24918961  1.21727154  1.56600199  1.29182229
  -5.19933758  1.60611295  1.24827047 -0.01335291  1.0734679  -0.20153818
   1.13469715  1.01197311  5.19933758  0.02611368  0.03046721 -5.19933758
  -0.03046721 -0.49455392 -5.19933758 -5.19933758  0.17054273 -5.19933758
   0.1397103  -5.19933758 -5.19933758  0.26414698 -0.25964336  0.8851225
   1.31151993  1.10010837  1.33406018  1.86671014  0.87379096  1.7975883
   1.11191399  1.6710678   1.54995944  1.73170685  1.72824114 -5.19933758
   5.19933758 -5.19933758 -1.14738102  1.79417582 -1.2546058  -5.19933758
  -5.1993

Entry [[-0.48877641  0.02365848  0.43319871  0.49368625  0.44621636 -0.09498341
  -0.07238908  5.19933758 -0.66903646 -0.48877641 -0.23272852  0.7708832
  -0.82438256 -0.97353423 -0.12883682  0.20598402  0.04792674  0.33695256
  -0.11634589  0.85593795  0.16544642  0.82681155  0.25065179  0.83240804
   1.24605324  0.49991423  0.67973065 -0.53973108 -1.02459239  0.30857767
   0.4561311   0.96049617  0.27858343  0.36205647  0.53863092  0.61159584
   0.42609755  0.78979972  0.48296366  1.84441983  1.59201259 -0.20153818
   2.11322227  1.39124933  1.02649084 -0.23720211  1.75149251 -5.19933758
  -0.24168045 -0.8695459  -5.19933758 -5.19933758 -1.19358872  1.41779714
   1.71249462 -5.19933758 -5.19933758 -1.23918288  1.23918288  1.09669855
   1.40509515  1.21805416  1.15648418  0.89983552  1.1146498   0.93843988
   0.91866935  0.52783186  0.86828298  0.55325328  0.62004409  1.09404034
   0.85496404 -0.85074052 -0.5012393   1.15577851 -0.46617156 -5.19933758
  -0.92974589 -0.27474314  0.1471

Entry [[-8.49086192e-01 -8.12964071e-01 -8.59455107e-01  8.49086192e-01
   6.72462250e-01 -8.27181185e-01 -8.94946776e-01  5.19933758e+00
   2.23795198e-01 -8.49086192e-01 -1.68980222e+00  6.28108370e-01
  -6.69036457e-01 -7.82317886e-01 -1.56298741e+00 -1.94526458e+00
  -8.19369964e-01 -9.09663138e-01  9.27523196e-01 -5.82087651e-01
   7.74551702e-01  1.21008605e+00 -5.19933758e+00 -1.03243930e+00
   2.06009448e-01 -2.12185259e-01  5.19933758e+00  2.03299608e-01
  -1.10648069e+00  1.10114551e+00  2.20041058e+00 -5.19933758e+00
   1.18476314e+00  1.81551733e+00  1.05447245e+00  1.59321882e+00
  -5.19933758e+00  1.13364272e+00  1.47994139e+00  5.18417988e-01
  -2.46163647e-01 -2.01538181e-01 -1.31801090e+00 -5.19933758e+00
   1.82049879e-01 -4.35507020e-01  3.04672093e-02 -5.19933758e+00
   5.19933758e+00 -1.08532491e+00 -5.19933758e+00 -5.19933758e+00
   5.19933758e+00 -5.19933758e+00 -9.00121575e-01 -5.19933758e+00
  -5.19933758e+00  5.19933758e+00 -5.19933758e+00  1.31801090e+00
   4

Entry [[ 8.70368029e-03  1.11346805e-02  1.91826756e-01 -8.70368029e-03
  -4.84089824e-01  7.51960202e-02  1.14258063e-01 -1.11724663e+00
   8.64097453e-01  8.70368029e-03 -7.55026178e-02  2.97441530e+00
  -1.17432799e-01 -1.22712631e-01 -1.08280553e-01  1.20821243e-01
   4.33485188e-03  2.08449263e-01 -1.93053350e-01  9.53349935e-01
   9.37745921e-02  2.05369374e-01 -1.66128844e-01 -2.65138840e-01
  -1.49617888e+00  1.29575098e+00  1.13831924e+00 -1.23774086e+00
  -3.04655324e+00  8.66824324e-01  2.61692303e-01  6.96507422e-01
   9.72543444e-01  3.12710962e-01  7.04144168e-01  1.39032490e-01
   1.01726417e+00  3.56102744e-02  1.01481473e-01 -1.82274142e+00
   6.57287829e-01  1.41779714e+00 -2.07754611e+00 -2.99338567e-01
  -1.08532193e+00 -2.31099134e+00 -5.19933758e+00  1.13364272e+00
   1.66128844e-01 -1.22985876e+00 -5.19933758e+00 -5.19933758e+00
   3.46234264e-01 -5.19933758e+00 -5.19933758e+00 -5.19933758e+00
  -5.19933758e+00  4.25957398e-01 -4.21197169e-01 -1.68599652e+00
   4

Entry [[-2.41680452e-01 -4.06876578e-01 -4.28132986e-01  2.46163647e-01
   4.60871983e-01 -3.93167076e-01 -3.41710963e-01  5.19933758e+00
   2.23795198e-01 -2.41680452e-01 -5.28399301e-01 -2.37202109e-01
  -1.66128844e-01 -1.62888073e-01 -6.24511582e-01 -5.13882947e-01
  -4.07778483e-01 -3.82522940e-01  4.82346975e-01  1.59095464e+00
   3.87362252e-01  1.93325705e-01 -6.20813679e-01 -4.55119596e-02
  -1.10803654e+00 -8.71458820e-02  6.47418523e-01  6.96849203e-02
  -1.35317169e-01 -4.17762342e-03 -5.19933758e+00 -5.19933758e+00
   1.36589018e-01 -6.39103071e-01 -6.53270994e-01 -1.56298741e+00
  -5.19933758e+00 -2.50558139e-02 -5.05694157e-01 -7.78747987e-01
  -1.00276922e+00 -2.01538181e-01  1.02669994e-01  2.38343468e-01
   3.09495750e-01  2.41680452e-01  3.04672093e-02 -5.19933758e+00
   6.20813679e-01 -1.48504741e-01 -5.19933758e+00 -5.19933758e+00
   7.18868053e-01 -5.19933758e+00 -2.59643357e-01 -5.19933758e+00
  -5.19933758e+00  7.64709674e-01 -7.64709674e-01 -7.62370689e-01
  -1

Entry [[ 1.45572018e-01  2.43027228e-01  7.64242438e-01 -1.45641008e-01
  -4.21349571e-02  3.87341461e-01  4.10105508e-01  5.19933758e+00
  -1.06077790e+00  1.45572018e-01 -5.61110483e-01 -3.00377940e-01
  -1.26205121e-02  1.46465472e-01 -6.19914376e-01 -4.98559477e-01
   2.39401457e-01  7.48577942e-01 -4.64647167e-01  3.65091821e-01
  -1.30507699e-01 -1.72677818e-01 -1.36069179e+00 -5.56960538e-01
  -1.33785390e-01  1.30557265e-02  5.84286196e-01 -3.04672093e-02
   2.41680452e-01  1.10782491e-01 -5.19933758e+00 -5.19933758e+00
   1.59867446e-01 -5.33401315e-01 -8.07116674e-01 -5.93724971e-01
  -5.19933758e+00 -2.69933549e-01 -1.83832830e-01 -6.38277766e-01
  -6.08386569e-01 -2.01538181e-01  2.61358716e-01  4.27024577e-01
   4.21197169e-01  6.20813679e-01  3.04672093e-02 -5.19933758e+00
   1.36069179e+00  2.59643357e-01 -5.19933758e+00 -5.19933758e+00
   1.45440760e+00 -5.19933758e+00 -6.63602988e-01 -5.19933758e+00
  -5.19933758e+00  1.45440760e+00 -1.44198872e+00 -4.06706374e-01
  -5

Entry [[-6.52794315e-01 -7.62552281e-01 -1.04395924e+00  6.58189040e-01
   5.46486593e-01 -7.56046133e-01 -8.18471989e-01  5.19933758e+00
  -5.08488059e-01 -6.52794315e-01 -4.91465971e-02  1.52906231e-01
  -3.18639364e-01 -4.49301791e-01 -8.40011021e-02 -3.88134278e-01
  -7.62852068e-01 -9.96953851e-01  1.12951546e+00  3.99241818e-01
   7.20629674e-01  4.91765212e-01  8.30510878e-01  7.74856006e-01
   4.06161467e-02 -6.53232053e-02  1.00258770e-01  4.78879341e-02
  -6.05060364e-01  7.56270242e-02 -5.19933758e+00 -5.19933758e+00
   1.50694507e-01 -9.95600493e-01 -1.16144595e-01 -3.80771221e-01
  -5.19933758e+00  3.58429274e-01 -8.38313794e-01 -1.53052922e-01
  -4.11705142e-01 -2.01538181e-01  1.22841964e+00  6.59569272e-01
   3.32405172e-01 -1.61718192e-01  3.04672093e-02 -5.19933758e+00
  -8.18285043e-01 -6.69036457e-01 -5.19933758e+00 -5.19933758e+00
  -4.54727137e-01 -5.19933758e+00  7.47335430e-01 -5.19933758e+00
  -5.19933758e+00 -2.77690440e-01  2.86747642e-01  4.33019262e-03
  -4

Output 130 [[0 0 0 1 0 0]]
Entry [[ 0.095886   -0.23990081 -0.744085   -0.095886    0.01228054 -0.19227966
  -0.3110088   5.19933758 -0.97646829  0.095886   -0.33700768 -0.49860802
   0.33525906  0.26976056 -0.32399535 -0.04377241 -0.24738529 -0.65856438
   0.89217928  0.15047595 -0.02417682 -0.21299522 -0.62081368 -0.07476103
  -0.18695935  0.06708521  0.15731068 -0.08448948  0.22290286  0.17887304
  -5.19933758 -5.19933758  0.2590545  -0.57368533 -0.68407051 -1.09795939
  -5.19933758 -0.22441525 -0.24702547 -0.64479439 -0.67996318 -0.20153818
   0.11174728  0.50919711  0.47602558  0.63778889  0.03046721 -5.19933758
   0.62081368  0.25964336 -5.19933758 -5.19933758  0.71886805 -5.19933758
  -0.25964336 -5.19933758 -5.19933758  0.76470967 -0.76470967 -0.42901317
  -0.53843354 -0.38983882  0.28800127 -0.56792885 -0.6314019  -1.12736506
  -0.08974165 -1.20268419 -1.08532491 -0.92546549 -0.44312888 -5.19933758
   0.35272896 -0.31559588  1.11329917 -0.59646421  0.55282947  0.29145459
   0.

Entry [[-0.78824133 -0.88071477 -0.91210209  0.79419257  0.78770252 -0.80916048
  -0.74045864  5.19933758  0.44509652 -0.78824133 -0.12215309 -0.14850474
  -0.77642176 -0.40538545 -0.14850474 -0.27317041 -0.90616141 -0.93059238
   0.74071413  1.50807188  0.85064735  0.50466684  0.83051088  1.25152396
  -0.12215309  0.01305573  0.10025877 -0.03046721 -0.62609901 -0.9191905
  -5.19933758 -5.19933758 -0.37282888 -0.69435393 -0.68738367 -0.55085837
  -5.19933758 -0.18659491 -0.76509973 -0.85648855 -0.41170514 -0.20153818
  -0.00546036  0.47267622  0.42119717 -0.14850474  0.03046721 -5.19933758
  -0.81828504 -0.66903646 -5.19933758 -5.19933758 -0.45472714 -5.19933758
   0.74733543 -5.19933758 -5.19933758 -0.27769044  0.28674764 -1.35710008
  -0.64206138 -0.69750375 -0.14696178 -0.30172951 -1.56298741 -1.19057475
  -0.57223596 -0.59611718 -0.69650742 -0.11858762 -0.52991224 -5.19933758
   0.29582843 -0.24616365 -0.5189784   0.24111823  0.1712352   0.8800818
   0.17790664  0.56886988  0.77142

Entry [[ 1.17769875e-01 -1.86714232e-02 -3.57212081e-01 -1.17827534e-01
   9.68038662e-02 -3.93815795e-02 -8.75833015e-02  5.19933758e+00
  -2.10428394e-01  1.17769875e-01  3.80692584e-01 -4.46316016e-01
   2.53020301e-01  2.41336079e-01  3.80692584e-01 -4.30794172e-02
  -2.79876496e-02 -2.98663494e-01  2.31176124e-01 -1.58819604e-01
  -7.09876270e-02 -4.86753952e-02  8.30510878e-01  1.14484870e+00
  -7.76421761e-01 -1.89537841e-01 -4.69252884e-01  1.80721446e-01
   3.01052468e-01 -3.31156561e-01 -5.19933758e+00 -5.19933758e+00
  -3.33047069e-01 -8.77921676e-01 -5.41346194e-01 -5.18417989e-01
  -5.19933758e+00 -4.08442086e-03 -5.99267825e-01 -1.74552141e-01
  -4.69252884e-01 -2.01538181e-01  2.77136932e-01  6.68440833e-01
   2.04633832e-01  5.48292376e-01  3.04672093e-02 -5.19933758e+00
  -8.18285043e-01  2.59643357e-01 -5.19933758e+00 -5.19933758e+00
  -4.54727137e-01 -5.19933758e+00  7.47335430e-01 -5.19933758e+00
  -5.19933758e+00 -2.77690440e-01  2.86747642e-01 -3.63291396e-01
  -6

Entry [[-0.84908619 -1.01283234 -1.30624043  0.84908619  0.69933818 -0.98663036
  -1.15733128  5.19933758 -5.19933758 -0.84908619 -0.16730556 -0.30037794
  -0.41644647 -0.4666853  -0.211615   -0.38813428 -1.02647591 -1.2600372
   1.39633346 -0.17666677  0.91472599  0.46574362  0.83051088  1.05086408
  -0.31389903  0.48877641  0.10025877 -0.5283993  -0.78428931 -0.9878665
  -5.19933758 -5.19933758 -0.9483412  -0.69786799 -0.77706899 -0.40494781
  -5.19933758 -1.73089416 -0.65826879 -0.3971035  -0.5461711  -0.20153818
  -0.26354391  0.29955283  1.00999017 -0.05515056  0.03046721 -5.19933758
  -0.81828504 -0.66903646 -5.19933758 -5.19933758 -0.45472714 -5.19933758
   0.74733543 -5.19933758 -5.19933758 -0.27769044  0.28674764 -0.64259655
  -0.84908619 -0.91431003 -0.12155336 -0.72668663 -0.5256965  -1.60099449
  -0.35296934 -0.62836814 -0.43550702 -1.00350369 -0.34277275 -5.19933758
   0.83667055 -0.83667055 -0.15881395 -0.32141966  0.56011838  1.02167624
  -0.2148797   0.22312998  0.73858

Entry [[ 0.19266387  0.07155129 -0.19900734 -0.18823244 -0.19844411  0.10961868
   0.13266251  5.19933758 -0.02956147  0.19266387  0.430518   -0.19266387
   0.23720211  0.32744174  0.430518    0.22787143  0.06613563 -0.1701459
  -0.19183962  0.08555493 -0.17285481 -0.2047067   0.83051088  0.48184043
  -0.43556885  0.2664817  -0.46925288 -0.30166777  0.17054273 -1.01857083
  -5.19933758 -5.19933758 -0.98813165 -0.83709315 -0.8712921  -0.63140189
  -5.19933758 -0.5511016  -0.58433433 -0.03100459 -0.39753603 -0.20153818
   0.47084647  0.74395748  0.71044124  0.68959106  0.03046721 -5.19933758
  -0.81828504  0.25964336 -5.19933758 -5.19933758 -0.45472714 -5.19933758
   0.74733543 -5.19933758 -5.19933758 -0.27769044  0.28674764 -0.31865424
  -0.61554563 -0.00546481  0.15456975 -0.93270468 -0.51394325 -0.79742717
  -0.4088591  -0.65268663 -1.15034938 -0.85109543 -0.62891322 -5.19933758
   0.57152174 -0.57151867  0.17597021 -0.62003958  1.13535395  1.02615758
  -0.12820624  0.56886988  0.5867

Entry [[-0.44029671 -0.62243378 -0.89416232  0.44029671  0.30420176 -0.60621602
  -0.64021996  5.19933758 -0.71723632 -0.44029671  0.03017696  0.54445862
  -0.18897075 -0.25058381 -0.00522217 -0.21857688 -0.62875872 -0.85457701
   0.82119424  0.57811243  0.5265891   0.28817609  0.83051088 -0.5834034
  -0.96049617  0.98141346  0.10025877 -1.08532491 -0.84908619 -1.43927088
  -5.19933758 -5.19933758 -2.22479621 -0.79210056 -1.12453819 -0.78727044
  -5.19933758 -1.5889411  -0.31986181 -0.40660791 -0.63483254 -0.20153818
   0.0824456   0.72113005  5.19933758 -0.01740802  0.03046721 -5.19933758
  -0.81828504 -0.66903646 -5.19933758 -5.19933758 -0.45472714 -5.19933758
   0.74733543 -5.19933758 -5.19933758 -0.27769044  0.28674764 -0.60555165
  -1.00999017 -0.6948124   0.10840378 -0.48228819 -0.80333069 -1.52177579
   0.07433552 -0.85338283 -0.72123359 -2.2464236  -0.42321943 -5.19933758
   5.19933758 -5.19933758 -0.57438476  0.00871457 -0.18599282  1.19309111
  -0.06968492  0.29128503  0.1015

Entry [[ 3.77208696e-01  1.33493455e-01 -4.55185781e-01 -3.77261495e-01
  -4.00546881e-01  1.46502700e-01  1.74160084e-01  5.19933758e+00
  -5.81723477e-01  3.77208696e-01  5.58810213e-01  3.76417408e-01
   4.69252884e-01  5.53970159e-01  5.58810213e-01  9.28301427e-02
   1.21403287e-01 -3.34691397e-01  2.63667174e-02  6.83399890e-04
  -2.95473290e-01 -4.65255237e-01  8.30510878e-01 -6.09980902e-01
  -9.26527813e-01  8.12217801e-01 -4.69252884e-01 -8.74319203e-01
   1.13388922e-01 -1.65886401e+00 -5.19933758e+00 -5.19933758e+00
  -9.79632217e-01 -9.94636373e-01 -1.34037938e+00 -1.30430494e+00
  -5.19933758e+00 -3.85154513e-01 -7.99914796e-01 -2.89800201e-01
  -4.69252884e-01 -2.01538181e-01  3.25451202e-01  7.15068905e-01
   1.62498072e+00  7.41594044e-01  3.04672093e-02 -5.19933758e+00
  -8.18285043e-01  2.59643357e-01 -5.19933758e+00 -5.19933758e+00
  -4.54727137e-01 -5.19933758e+00  7.47335430e-01 -5.19933758e+00
  -5.19933758e+00 -2.77690440e-01  2.86747642e-01 -5.29612402e-01
  -8

Entry [[ 0.62210118  0.87545039  1.19619514 -0.62231196 -0.94630351  0.7381377
   0.73532058  5.19933758 -0.73738247  0.62210118  0.8475271   1.60735611
   0.55112554  0.37683839  0.8475271   0.46467438  0.87730006  1.18952022
  -0.83647167 -0.41681664 -0.64929564 -0.3254974   5.19933758 -1.26119418
  -0.16171819  0.7257128  -0.4259574  -0.7829466  -0.01305573 -0.39297677
   0.21031686 -5.19933758 -0.54678194  0.27290544  0.23106904  0.31621214
  -5.19933758 -0.05403741  0.35584379  1.04303091  1.34073272 -0.20153818
  -0.20508556  1.3393874   1.41906285  0.50758783  0.03046721 -5.19933758
  -5.19933758  0.06968492 -5.19933758 -5.19933758 -0.83051088 -5.19933758
   1.10916012 -5.19933758 -5.19933758 -0.61554563  0.61554563  0.53442197
   1.11853028 -0.94852909  1.08981639  0.48020914  0.70776658  0.3639414
   0.59134712  0.00648923  0.47882848 -0.12978867  0.4887236  -5.19933758
   1.26773063 -1.23248603  1.54783546 -2.03268573  1.90547163  0.43352074
   0.36477713  0.88358092  0.95792

Entry [[ 0.73432198  0.78749271  0.98283899 -0.73453583 -0.44451255  0.7802937
   0.78970072  5.19933758 -0.28194857  0.73432198  0.50848806 -0.80629901
   0.72116487  0.69788184  0.50848806  0.65507471  0.78822124  0.98946775
  -0.86843792 -0.84964253 -0.78390453 -0.56670532 -0.48411131  0.27659569
   0.00870368 -0.57913216 -0.63961187  0.56886988  0.82438256  1.84636868
   5.19933758 -5.19933758  1.88555233  2.20041058  1.77619292  2.67205881
  -5.19933758  1.7515258   2.00224197  1.97198682  0.70056636 -0.20153818
  -0.96742157  1.08532491 -0.17495994  0.96742157  0.03046721 -5.19933758
   0.48387833  0.74159404 -5.19933758 -5.19933758  0.5842862  -5.19933758
  -0.15310637 -5.19933758 -5.19933758  0.63696487 -0.63696487  1.59723348
   0.931815    1.66572698  1.57004572  1.66445663  0.72870802  1.70016325
   1.15823406  1.47895596  1.66371091  1.40625774  1.58417465 -5.19933758
  -0.41170514  0.49860802 -1.20460246  0.94956163 -0.82424886 -5.19933758
  -0.51841799 -0.06426807 -0.7034

Entry [[ 0.30493368  0.46767983  0.64922905 -0.30037794 -0.63779793  0.42822606
   0.42337927  5.19933758 -1.17597635  0.30493368  0.35549042  1.18476314
   0.16612884  0.03536908  0.35549042 -0.01669152  0.4681742   0.65667012
  -0.58130048 -0.56601961 -0.378598    0.06950972  0.50354189 -1.21612051
  -0.61029461  0.5707055  -0.05224518 -0.61444882 -0.41644647  0.56731765
  -0.05119324 -5.19933758 -0.5593446  -1.30329683  0.49593181  0.02811828
  -5.19933758 -1.79806227 -1.33480892  0.7493809   1.05550743 -0.20153818
  -1.61827356 -1.05439854  1.13640516  0.11776987  0.03046721 -5.19933758
  -0.49860802 -0.36943226 -5.19933758 -5.19933758 -0.20598125 -5.19933758
   0.49860802 -5.19933758 -5.19933758 -0.07841241  0.08714588  0.46507578
   0.81307559 -0.60759011 -1.26660463  0.43166603  0.27309187  0.33284071
  -1.30553308  0.18683988  0.02620869 -0.24501693 -1.29181588 -5.19933758
   0.95607841 -0.95560582  2.21522769 -2.04249277  2.20736114  0.09352144
   0.31863936  0.7609258   1.006

Entry [[-0.05224518  0.06769083  0.49365486  0.05224518  0.32019026  0.15767991
   0.22963343  5.19933758 -0.01144352 -0.05224518 -0.16341422  0.24520389
  -0.2622162  -0.23242326 -0.2076912   0.10651576  0.07350976  0.48065268
  -0.31651883  0.37494657  0.12912736  0.31813346 -0.2237952   0.74730435
   0.43358263 -0.22449009  0.19075731  0.21558972 -0.09005848  0.9265376
   0.65123531 -5.19933758  0.95361654  0.61324934  0.77822867  0.6064879
  -5.19933758  0.65337379  0.55329022 -0.3258146   0.58211149 -0.20153818
  -1.97198682 -0.47993024  0.16983885  0.2119117   1.14195621 -5.19933758
   0.2237952  -0.0435316  -5.19933758 -5.19933758  0.34623426  0.70206458
   0.5842862  -5.19933758 -5.19933758 -0.16171819  0.16612884  0.04552509
   0.83879228 -1.30347752  0.75100083  0.54022202  0.56061697  0.74577495
   0.64551585  0.59385054  0.57667684  0.32469073  0.59738838 -5.19933758
   0.02978925  0.07472967 -1.20166777  0.64692341 -0.47350304 -0.67168831
  -0.62154822 -0.2290673  -0.40084

Entry [[-1.4544076  -1.47994139 -1.56298741  1.4544076   1.65847206 -1.47994139
  -1.47994139  5.19933758  0.2237952  -1.4544076  -1.03941642 -0.68545705
  -1.18476314 -1.17602889 -1.18476314 -1.15034938 -1.47994139 -1.47994139
   1.36069179  0.34623426  1.47994139  0.70764351 -0.29128503  1.2180763
   0.61029461 -0.44990661  0.93999091  0.44029671 -0.96742157  0.49860802
   1.23918288  0.96049617  0.70764351  0.95361654  0.47416806  1.33925092
   0.71324455  0.63944911  0.7061004   0.49860802  0.95173051 -0.20153818
  -1.20250826 -0.31863936 -0.03482132 -0.54852228  0.03046721 -5.19933758
   0.29128503 -0.96742157 -5.19933758 -5.19933758  0.4307273   0.70206458
  -0.0435316  -5.19933758 -5.19933758 -0.07841241  0.08714588  0.86634499
   1.36014648  0.76594389  0.77530708  0.72053632  1.13848127  0.79771456
   0.53575498  0.3891119   0.88974232  0.27320115  0.65487814  1.27556537
  -0.27317041  0.37409541 -1.97198682  1.86273187 -1.38299413 -1.00999017
  -1.59321882 -5.19933758 -1.3557

Entry [[-1.4544076  -1.47994139 -1.56298741  1.4544076   1.65847206 -1.47994139
  -1.47994139  5.19933758  0.2237952  -1.4544076  -1.03941642 -0.68545705
  -1.18476314 -1.17602889 -1.18476314 -1.15034938 -1.47994139 -1.47994139
   1.36069179  0.34623426  1.47994139  0.70764351 -0.29128503  1.22166229
   0.61029461 -0.44990661  0.93999091  0.44029671 -0.96742157  0.49860802
   1.23918288 -5.19933758  0.70764351  0.95361654  0.45984858  1.30473784
  -5.19933758  0.62242089  0.69197376  0.49860802  0.63016981 -0.20153818
  -1.20250826 -0.31863936 -0.03482132 -0.54852228  0.03046721 -5.19933758
   0.29128503 -0.96742157 -5.19933758 -5.19933758  0.45472714 -5.19933758
  -0.0435316  -5.19933758 -5.19933758  0.52371407 -0.52371407  0.40103329
   1.16965107  0.75681544  0.70887943  0.71518272  1.05627308  0.76374424
   0.5180828   0.26946915  0.83459878  0.27316152  0.62834363 -5.19933758
  -0.27317041  0.37409541 -1.97198682  1.86273187 -1.38299413 -1.00999017
  -1.59321882 -5.19933758 -1.374

Entry [[ 0.19266387  0.32431099  0.25133892 -0.18823244 -0.41222708  0.26137021
   0.24564642  5.19933758  0.2237952   0.19266387  0.58672702  0.8198669
   0.23720211  0.10340834  0.58672702  0.9574597   0.32884781  0.25390397
  -0.20441281  0.18123873 -0.27716678  0.24200484  5.19933758  1.36971079
   0.56694732  0.10901014 -0.33211492 -0.12653865 -0.24317431 -1.9363776
   0.15562243  1.16738344 -1.50647826  0.24689448 -1.77300223  0.20296744
   1.29754293 -0.72451438  0.37563011 -0.2114029   1.19111363 -0.20153818
   0.88714656  1.30421488  0.52340213  0.20820431  0.03046721 -5.19933758
  -5.19933758 -0.29355597 -5.19933758 -5.19933758 -1.19358872  0.70206458
   1.10916012 -5.19933758 -5.19933758 -0.98848196  0.99560019 -0.5898813
   0.925098    0.40697306  1.00869482 -1.56518207  0.64196443 -0.49368625
   0.75916526 -1.78555083  0.34583743 -1.46705494  0.46991227  1.53412054
   0.39753603 -0.36012989  1.94395107 -1.80098709  2.36626234  1.40360847
   0.0851299   0.23271138  2.845629

Entry [[-1.29754293 -0.74159404 -0.03921686  1.29754293  1.32310969 -0.9085474
  -0.86711068  5.19933758  0.06532321 -1.29754293 -0.1838047   0.38872997
  -1.52411431 -1.98560221 -0.23272852 -0.4307273  -0.68804632 -0.27052752
   0.50268948  1.24116039  0.800484    2.46559262  5.19933758  0.94059203
   0.63653105 -0.81935764  0.41170514  0.81940753 -1.15034938 -0.5535876
  -5.19933758  1.30770843 -1.50647826 -5.19933758  0.095886   -0.9265376
   0.80073411 -0.72451438 -5.19933758  1.30770843 -0.24616365 -0.20153818
   0.88714656 -5.19933758 -0.41856484 -1.52015421  1.14195621 -5.19933758
  -5.19933758 -5.19933758 -5.19933758 -5.19933758 -5.19933758  1.00999017
   1.71249462 -5.19933758 -5.19933758 -5.19933758  5.19933758  0.70764351
  -0.35085858  0.40697306 -5.19933758  0.28221615 -0.95361654 -0.49368625
  -5.19933758 -0.14850474 -1.62498072 -1.46705494 -5.19933758  1.4535086
  -0.73513453  0.80729565 -0.66008363  0.14017027 -0.0554047  -0.15618492
  -1.30920789 -0.69914278 -0.4343444

Entry [[-1.77203415e+00 -1.77203415e+00 -1.44198872e+00  1.77203415e+00
   1.41568846e+00 -1.79335194e+00 -1.79335194e+00  5.19933758e+00
  -5.19933758e+00 -1.77203415e+00 -1.29754293e+00 -1.15667937e+00
  -5.19933758e+00 -5.19933758e+00 -5.19933758e+00 -5.19933758e+00
  -1.79335194e+00 -1.73166440e+00  1.71249462e+00 -2.32728519e-01
   1.73166440e+00  4.35179893e-03  6.31401894e-01  1.12851354e+00
  -4.07983568e-02  6.80939875e-01  7.39481369e-01 -7.36762223e-01
  -1.37175767e+00 -5.19933758e+00  1.96815862e-01 -5.19933758e+00
  -9.02296787e-01 -1.00329564e-01 -2.69264170e+00  4.02015345e-01
  -5.19933758e+00 -9.20945166e-02 -5.97932323e-06 -1.54616597e+00
   1.87768191e+00 -2.01538181e-01  1.45200879e+00  9.33129937e-01
   1.33008829e+00 -4.45096525e-01  1.82694304e+00 -5.19933758e+00
  -6.26099012e-01 -1.27760457e+00 -5.19933758e+00 -5.19933758e+00
  -1.36069179e+00  1.27760457e+00  2.27411316e+00 -5.19933758e+00
  -5.19933758e+00 -1.36406992e+00  1.36406992e+00 -2.46675026e+00
   1

Entry [[ 1.56626113  1.4433162   1.47761503 -1.56659727 -1.30999473  2.04056611
   2.03827383 -1.11724663  0.3062476   1.56626113  1.8289967  -0.63961933
   1.50300996  1.53136344  1.8289967   1.33863285  1.44329024  1.49234932
  -2.07501304 -1.61162329 -1.57295243 -1.43412191  0.03482132 -1.75157962
  -1.71249462  1.46705494 -2.2522646  -1.4930784   1.71249462 -0.24213213
  -0.25404889  0.69650742 -0.63429784 -1.14403597  0.28453531 -0.1787735
   1.01726417 -1.34066618 -1.16830877  0.86579882  0.30208416  1.41779714
  -0.5969496  -0.26761676 -0.80618031  1.57792286 -5.19933758  1.13364272
  -0.03046721  1.75149251 -5.19933758 -5.19933758  0.17054273 -5.19933758
  -5.19933758 -5.19933758 -5.19933758  0.26414698 -0.25964336  0.49620178
   0.19404311 -1.0039993  -0.63565802  0.52822581 -0.07998009 -0.25814735
  -1.02698991  0.10770903 -0.16580198 -0.46380486 -1.10453795 -5.19933758
  -0.12653865 -0.06532321  0.06063587 -0.2917466   0.32643409 -0.44054605
   0.95358369  1.1973592   0.9178

Entry [[ 6.38246101e-01  1.26169894e+00  2.33204723e+00 -6.38782061e-01
   4.47263015e-02  1.24242155e+00  1.23479992e+00 -2.80820281e+00
   3.15166765e-01  6.38246101e-01  4.08432098e-03 -2.53643404e+00
   3.09495750e-01  1.91699102e-01  2.61136788e-02  5.19299085e-01
   1.26323253e+00  2.32892947e+00 -1.45516285e+00 -6.81786198e-01
  -7.48273004e-01 -4.24740456e-01 -1.08954270e+00  2.02803600e-01
   1.73915319e+00  1.12834145e+00 -1.23071415e+00  8.83433567e-02
   1.58893512e+00  5.19933758e+00  1.17835326e+00  2.55465689e+00
   5.19933758e+00  2.71591599e+00  5.19933758e+00  7.47523278e-01
   2.00262269e+00  5.19933758e+00  1.95077083e+00 -1.90457105e+00
  -2.46163647e-01 -5.19933758e+00 -1.84475105e+00 -5.19933758e+00
  -3.07467934e+00 -5.19933758e+00  1.62498072e+00  2.79385806e+00
   1.08925451e+00  1.36198905e+00 -5.19933758e+00 -5.19933758e+00
   9.08856409e-01  1.41779714e+00  2.64146977e-01 -5.19933758e+00
  -5.19933758e+00 -3.74095410e-01  3.74095410e-01  1.13774776e+00
  -1

Entry [[ 1.69941663  1.79876708  1.92014146 -1.69991993 -1.97211861  1.92118784
   1.94123402  5.19933758 -1.12680722  1.69941663  1.44162705 -0.37690438
   1.60088661  1.62592685  1.43934691  1.2046716   1.79875483  1.92032407
  -1.94447954 -1.79516602 -1.69169527 -1.3720449  -1.77203415 -1.52730897
  -0.65782506  0.36523664 -1.32842734 -0.40271422  2.37796818  0.4695227
  -0.22817162 -5.19933758  0.59303902 -1.28704377  0.43315737 -0.26036332
  -5.19933758  0.70999587 -1.29967349  0.17118985 -0.08094736 -0.20153818
  -0.98150401 -1.15107188  0.83727813  2.60760515  0.03046721 -5.19933758
   1.77203415  1.75149251 -5.19933758 -5.19933758  1.83861236 -5.19933758
  -0.8122178  -5.19933758 -5.19933758  1.83861236 -1.83861236  0.19306546
  -0.16723894  1.04063434 -1.28167249  0.66398691 -0.197127    0.87094708
  -1.17882621  0.46427105 -0.26661084  0.56691563 -1.19890481 -5.19933758
   0.68600089 -0.68600085  0.361467   -0.48224758 -0.11909961 -0.58157559
   0.61152863  1.37234518  0.0902

Entry [[ 1.92148812  2.00028334  1.16049926 -1.92219528 -1.88108242  1.57773669
   1.59391375 -0.85534332  1.96438862  1.92148812  1.75722246  0.04788877
   1.951459    1.97251566  1.75722246  2.37324201  2.00026543  1.16479798
  -1.57541812 -1.4629783  -1.96850968 -1.3944184  -0.39283081 -0.752359
  -1.14241789  1.0416706  -1.64149625 -0.29587389  2.55436135  0.76027487
  -0.13048464  1.09320101  0.90361265 -0.09013461  0.85737736 -0.05204678
   0.48877641  0.98563003 -0.09362833  0.63506827  0.68970874 -0.20153818
   1.66855584 -0.17337597 -1.24496356  1.3393807   1.91450583  0.86163412
   0.40225007  1.75149251 -5.19933758 -5.19933758 -0.83051088  1.69393425
   1.50647826 -5.19933758 -5.19933758 -1.3180109   1.3180109   0.16068228
   0.45141602  0.87802959 -0.55722831  0.597122    0.17551094  0.99106064
  -0.70440869  1.03878714 -0.03358444  1.22204201  0.03818993  1.13364272
  -0.79317108  0.58889289 -0.83857694  0.84449162 -1.10383713  1.41492467
   1.28552863  1.4503756  -0.84819

Entry [[ 1.20641227  1.06338505 -0.2671282  -1.20847629 -1.08146897  0.93416864
   0.81026284  5.19933758  0.83833341  1.20641227  1.20641947  0.19876951
   1.22378084  1.23517164  1.20578491  1.271198    1.0633384  -0.15603277
  -0.52119562 -1.87601234 -1.21415488 -1.01942345  0.03482132  0.26801638
  -0.80184671  0.91789443 -1.10916012 -1.01383036  1.13354931 -3.16955416
  -0.39662689 -5.19933758 -1.11700899 -1.0099936  -2.70626605 -0.34745369
  -5.19933758 -0.9947464  -0.9702115  -2.199364   -1.35381073 -0.20153818
   0.53908646 -0.05093867  1.98833349  1.38302154  0.03046721 -5.19933758
  -0.03046721  1.15882438 -5.19933758 -5.19933758  0.17054273 -5.19933758
   0.1397103  -5.19933758 -5.19933758  0.26414698 -0.25964336 -2.12716477
  -1.51402044  0.09749665 -0.33631111 -2.59892574 -0.3405391  -0.76053986
  -0.7359913  -2.63717012 -0.37601575 -1.11612903 -0.9365541  -5.19933758
   1.80071494 -1.74811685 -0.18404983  0.69937917 -0.43478398  5.19933758
   0.70206458  5.19933758 -0.163

In [19]:
#https://github.com/scikit-multiflow/scikit-multiflow/blob/a7e316d/src/skmultiflow/meta/classifier_chains.py#L273
import numpy as np
import copy
from sklearn.linear_model import LogisticRegression, SGDClassifier
from skmultiflow.core import BaseSKMObject, ClassifierMixin, MetaEstimatorMixin, MultiOutputMixin
from skmultiflow.utils import check_random_state

class ClassifierChain(BaseSKMObject, ClassifierMixin, MetaEstimatorMixin, MultiOutputMixin):
    """ Classifier Chains for multi-label learning.

    Parameters
    ----------
    base_estimator: skmultiflow.core.BaseSKMObject or sklearn.BaseEstimator (default=LogisticRegression)
        Each member of the ensemble is an instance of the base estimator

    order : str (default=None)
        `None` to use default order, 'random' for random order.

    random_state: int, RandomState instance or None, optional (default=None)
        If int, random_state is the seed used by the random number generator;
        If RandomState instance, random_state is the random number generator;
        If None, the random number generator is the RandomState instance used by `np.random`.

    Examples
    --------
    >>> from skmultiflow.data import make_logical
    >>>
    >>> X, Y = make_logical(random_state=1)
    >>>
    >>> print("TRUE: ")
    >>> print(Y)
    >>> print("vs")
    >>>
    >>> print("CC")
    >>> cc = ClassifierChain(SGDClassifier(max_iter=100, loss='log', random_state=1))
    >>> cc.fit(X, Y)
    >>> print(cc.predict(X))
    >>>
    >>> print("RCC")
    >>> cc = ClassifierChain(SGDClassifier(max_iter=100, loss='log', random_state=1), order='random', random_state=1)
    >>> cc.fit(X, Y)
    >>> print(cc.predict(X))
    >>>
    TRUE:
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]
    vs
    CC
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]
    RCC
    [[1. 0. 1.]
     [1. 1. 0.]
     [0. 0. 0.]
     [1. 1. 0.]]



    Notes
    -----
    Classifier Chains [1]_ is a popular method for multi-label learning. It exploits correlation between labels
    by incrementally building binary classifiers for each label.

    scikit-learn also includes 'ClassifierChain'. A difference is probabilistic extensions are included here.


    References
    ----------
    .. [1] Read, Jesse, Bernhard Pfahringer, Geoff Holmes, and Eibe Frank. "Classifier chains for multi-label
       classification." In Joint European Conference on Machine Learning and Knowledge Discovery in Databases,
       pp. 254-269. Springer, Berlin, Heidelberg, 2009.

    """

    # TODO: much of this can be shared with Regressor Chains, probably should use a base class to inherit here.

    def __init__(self, base_estimator=LogisticRegression(), order=None, random_state=None):
        super().__init__()
        self.base_estimator = base_estimator
        self.order = order
        self.random_state = random_state
        self.chain = None
        self.ensemble = None
        self.L = None
        self._random_state = None   # This is the actual random_state object used internally
        self.__configure()

    def __configure(self):
        self.ensemble = None
        self.L = -1
        self._random_state = check_random_state(self.random_state)

    def fit(self, X, y, classes=None, sample_weight=None):
        """ Fit the model.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The features to train the model.

        y: numpy.ndarray of shape (n_samples, n_targets)
            An array-like with the labels of all samples in X.

        classes: Not used (default=None)

        sample_weight: Not used (default=None)

        Returns
        -------
        self

        """
        N, self.L = y.shape
        L = self.L
        N, D = X.shape

        self.chain = np.arange(L)
        if self.order == 'random':
            self._random_state.shuffle(self.chain)

        # Set the chain order
        y = y[:, self.chain]

        # Train
        self.ensemble = [copy.deepcopy(self.base_estimator) for _ in range(L)]
        XY = np.zeros((N, D + L-1))
        XY[:, 0:D] = X
        XY[:, D:] = y[:, 0:L - 1]
        for j in range(self.L):
            self.ensemble[j].fit(XY[:, 0:D + j], y[:, j])
        return self

    def partial_fit(self, X, y, classes=None, sample_weight=None):
        """ Partially (incrementally) fit the model.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The features to train the model.

        y: numpy.ndarray of shape (n_samples)
            An array-like with the labels of all samples in X.

        classes: Not used (default=None)

        sample_weight: NOT used (default=None)

        Returns
        -------
        self

        """
        if self.ensemble is None:
            # This is the first time that the model is fit
            self.fit(X, y)
            return self

        N, self.L = y.shape
        L = self.L
        N, D = X.shape

        # Set the chain order
        y = y[:, self.chain]

        XY = np.zeros((N, D + L-1))
        XY[:, 0:D] = X
        XY[:, D:] = y[:, 0:L - 1]
        for j in range(L):
            self.ensemble[j].partial_fit(XY[:, 0:D + j], y[:, j])

        return self

    def predict(self, X):
        """ Predict classes for the passed data.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The set of data samples to predict the labels for.

        Returns
        -------
        A numpy.ndarray with all the predictions for the samples in X.

        """
        N, D = X.shape
        Y = np.zeros((N, self.L))
        for j in range(self.L):
            if j > 0:
                X = np.column_stack([X, Y[:, j-1]])
            Y[:, j] = self.ensemble[j].predict(X)

        # Unset the chain order (back to default)
        return Y[:, np.argsort(self.chain)]

    def predict_proba(self, X):
        """ Estimates the probability of each sample in X belonging to each of the class-labels.

        Parameters
        ----------
        X : numpy.ndarray of shape (n_samples, n_features)
            The matrix of samples one wants to predict the class probabilities for.

        Returns
        -------
        A numpy.ndarray of shape (n_samples, n_labels), in which each outer entry is associated with the X entry of the
        same index. And where the list in index [i] contains len(self.target_values) elements, each of which represents
        the probability that the i-th sample of X belongs to a certain class-label.

        Notes
        -----
        Returns marginals [P(y_1=1|x),...,P(y_L=1|x,y_1,...,y_{L-1})]
        i.e., confidence predictions given inputs, for each instance.

        This function suitable for multi-label (binary) data
        only at the moment (may give index-out-of-bounds error if
        uni- or multi-target (of > 2 values) data is used in training).
        """
        N, D = X.shape
        Y = np.zeros((N, self.L))
        for j in range(self.L):
            if j > 0:
                X = np.column_stack([X, Y[:, j-1]])
            Y[:, j] = self.ensemble[j].predict_proba(X)[:, 1]
        return Y

    def reset(self):
        self.__configure()
        return self

    def _more_tags(self):
        return {'multioutput': True,
                'multioutput_only': True}


def P(y, x, cc, payoff=np.prod):
    """ Payoff function, P(Y=y|X=x)

        What payoff do we get for predicting y | x, under model cc.

        Parameters
        ----------
        x: input instance
        y: its true labels
        cc: a classifier chain
        payoff: payoff function

        Returns
        -------
        A single number; the payoff of predicting y | x.
    """
    D = len(x)
    L = len(y)

    p = np.zeros(L)
    xy = np.zeros(D + L)
    xy[0:D] = x.copy()
    for j in range(L):
        P_j = cc.ensemble[j].predict_proba(xy[0:D+j].reshape(1, -1))[0]  # e.g., [0.9, 0.1] wrt 0, 1
        xy[D+j] = y[j]                                           # e.g., 1
        p[j] = P_j[y[j]]                                         # e.g., 0.1
                                                                 # or, y[j] = 0 is predicted with probability p[j] = 0.9
    return payoff(p)

In [22]:
#Rank 3
class ProbabilisticClassifierChain(ClassifierChain):
    #order=[6,4,1,5,2,3]
    def __init__(self, base_estimator=LogisticRegression(), order=None, random_state=None):
            super().__init__(base_estimator=base_estimator, order=order, random_state=random_state)
            
    def predict(self, X, num_top_probs=3):
        N, D = X.shape
        Yp = np.zeros((N, self.L))
        top_probs = []  
        for n in range(N):          
            label_probs = []          
            for b in range(2 ** self.L):
                y_ = np.array(list(map(int, np.binary_repr(b, width=self.L))))           
                w_ = P(y_, X[n], self)                
                label_probs.append((y_, w_))       
            label_probs.sort(key=lambda x: x[1], reverse=True)           
            top_probs.append(label_probs[:num_top_probs])
            Yp[n, :] = label_probs[0][0]
        return Yp, top_probs

In [23]:
predict_times = []
cv = LeaveOneOut()
y_true, y_pred = list(), list()
count = 0
for train_ix, test_ix in cv.split(X_orig):
        count += 1
        X_train, X_test = X_orig[train_ix, :], X_orig[test_ix, :]
        y_train, y_test = Y_orig[train_ix], Y_orig[test_ix]
        X_train_folds = transformer.fit_transform(X_train) 
        X_test_folds= transformer.transform(X_test) 
        print("Entry", X_test_folds)
        clf = ProbabilisticClassifierChain(DecisionTreeClassifier(criterion='entropy',random_state=17, min_samples_leaf=10                                              ))
        clf.fit(X_train_folds, y_train)
        predict_start_time = time()
        yhat = clf.predict(X_test_folds)
        predict_end_time = time()
        predict_duration = predict_end_time - predict_start_time
        predict_times.append(predict_duration)
        print("Output", count,yhat)
        y_true.append(y_test[0])
        y_pred.append(yhat[0].ravel())
        print("Time:",predict_times)
print("Mean Time:", sum(predict_times) / len(predict_times))
print("f1",f1_score(y_true, y_pred,average='macro'))
print("acc",accuracy_score(y_true, y_pred))
print("precision", precision_score(y_true, y_pred,average='macro'))
print("hamming",hamming_loss(y_true, y_pred))
print(skm.multilabel_confusion_matrix(y_true, y_pred))

Entry [[-5.19933758e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
   1.27132003e+00 -5.19933758e+00 -5.19933758e+00  5.19933758e+00
  -5.19933758e+00 -5.19933758e+00 -2.87416864e+00 -1.41800799e+00
  -5.19933758e+00 -1.83102868e+00 -5.19933758e+00 -1.63272919e+00
  -5.19933758e+00 -5.19933758e+00  5.19933758e+00  2.64832565e-01
   5.19933758e+00 -5.19933758e+00 -3.37007679e-01  1.31328749e+00
   1.78543910e-01 -2.54694753e-01  1.40391085e+00  2.43263067e-01
  -1.41779714e+00 -9.64642612e-01 -1.14953089e-01 -5.19933758e+00
  -8.06570002e-01 -5.48466372e-02 -3.68580607e-01 -3.63067624e-02
  -5.19933758e+00  1.67459499e-02  1.61790463e-02  6.58790415e-01
   8.86987878e-01 -2.01538181e-01  1.49471900e+00  9.87218257e-01
   1.42553491e-01 -9.88481957e-01  2.21282487e+00 -5.19933758e+00
   3.37007679e-01 -1.42576847e+00 -5.19933758e+00 -5.19933758e+00
  -1.36069179e+00  1.69393425e+00  2.67534323e+00 -5.19933758e+00
  -5.19933758e+00 -1.42978834e+00  1.42978834e+00  1.89588223e-01
   6